default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres 
  pool: 5

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  password: <%= ENV['blog_DATABASE_PASSWORD'] %>
